### ISSUE TITLE
对项目 vuex-module-decorators 转换后多处报文件转换异常

### ISSUE THREAD

**Issue by CaoMeiYouRen** [thx/gogocode#106]
- version: 0.2.23
- playground demo: 
- your description:  对项目 [vuex-module-decorators](https://github.com/championswimmer/vuex-module-decorators#readme) 转换后多处报文件转换异常。
```sh
gogocode -s ./src -t gogocode-plugin-vue -o ./src-out -i
```

```txt
文件转换异常，规则：api，文件：D:\Projects\typescript项目\vuex-module-decorators\src\module\index.ts TypeError: scriptAST.replace is not a function
    at Object.module.exports [as rule] (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\src\api.js:10:15)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\index.js:33:28
    at Array.reduce (<anonymous>)
    at transform (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\index.js:28:26)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:194:22
    at Array.forEach (<anonymous>)
    at execTransforms (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:175:13)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:363:49
    at Array.forEach (<anonymous>)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:351:23
文件转换异常，规则：router，文件：D:\Projects\typescript项目\vuex-module-decorators\src\module\index.ts TypeError: ast.find is not a function
    at Object.module.exports [as rule] (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\src\vue-router.js:37:29)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\index.js:33:28
    at Array.reduce (<anonymous>)
    at transform (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\index.js:28:26)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:194:22
    at Array.forEach (<anonymous>)
    at execTransforms (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:175:13)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:363:49
    at Array.forEach (<anonymous>)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:351:23
文件转换异常，规则：vuex，文件：D:\Projects\typescript项目\vuex-module-decorators\src\module\index.ts TypeError: sourceAst.replace is not a function
    at Object.module.exports [as rule] (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\src\vue-vuex.js:3:15)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\index.js:33:28
    at Array.reduce (<anonymous>)
    at transform (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\index.js:28:26)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:194:22
    at Array.forEach (<anonymous>)
    at execTransforms (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:175:13)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:363:49
    at Array.forEach (<anonymous>)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:351:23
文件转换异常，规则：globalApiTreeshaking，文件：D:\Projects\typescript项目\vuex-module-decorators\src\module\index.ts TypeError: script.replace is not a function
    at Object.module.exports [as rule] (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\src\global-api-treeshaking.js:7:12)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\index.js:33:28
    at Array.reduce (<anonymous>)
    at transform (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\index.js:28:26)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:194:22
    at Array.forEach (<anonymous>)
    at execTransforms (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:175:13)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:363:49
    at Array.forEach (<anonymous>)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:351:23
文件转换异常，规则：asyncComponents，文件：D:\Projects\typescript项目\vuex-module-decorators\src\module\index.ts TypeError: script.replace is not a function
    at Object.module.exports [as rule] (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\src\async-components.js:8:10)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\index.js:33:28
    at Array.reduce (<anonymous>)
    at transform (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\index.js:28:26)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:194:22
    at Array.forEach (<anonymous>)
    at execTransforms (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:175:13)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:363:49
    at Array.forEach (<anonymous>)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:351:23
文件转换异常，规则：customDirectives，文件：D:\Projects\typescript项目\vuex-module-decorators\src\module\index.ts TypeError: script.find is not a function
    at Object.module.exports [as rule] (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\src\custom-directives.js:48:12)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\index.js:33:28
    at Array.reduce (<anonymous>)
    at transform (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\index.js:28:26)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:194:22
    at Array.forEach (<anonymous>)
    at execTransforms (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:175:13)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:363:49
    at Array.forEach (<anonymous>)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:351:23
文件转换异常，规则：children，文件：D:\Projects\typescript项目\vuex-module-decorators\src\module\index.ts TypeError: script.find is not a function
    at Object.module.exports [as rule] (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\src\children.js:34:16)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\index.js:33:28
    at Array.reduce (<anonymous>)
    at transform (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\index.js:28:26)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:194:22
    at Array.forEach (<anonymous>)
    at execTransforms (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:175:13)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:363:49
    at Array.forEach (<anonymous>)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:351:23
文件转换异常，规则：emitsOptions，文件：D:\Projects\typescript项目\vuex-module-decorators\src\module\index.ts TypeError: sourceAst.find is not a function
    at Object.module.exports [as rule] (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\src\emits-option.js:28:35)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\index.js:33:28
    at Array.reduce (<anonymous>)
    at transform (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\index.js:28:26)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:194:22
    at Array.forEach (<anonymous>)
    at execTransforms (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:175:13)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:363:49
    at Array.forEach (<anonymous>)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:351:23
文件转换异常，规则：filters，文件：D:\Projects\typescript项目\vuex-module-decorators\src\module\index.ts TypeError: script.find is not a function
    at Object.module.exports [as rule] (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\src\filters.js:30:12)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\index.js:33:28
    at Array.reduce (<anonymous>)
    at transform (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\index.js:28:26)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:194:22
    at Array.forEach (<anonymous>)
    at execTransforms (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:175:13)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:363:49
    at Array.forEach (<anonymous>)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:351:23
文件转换异常，规则：functionalComponents，文件：D:\Projects\typescript项目\vuex-module-decorators\src\module\index.ts TypeError: script.has is not a function
    at Object.module.exports [as rule] (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\src\functional-components.js:7:33)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\index.js:33:28
    at Array.reduce (<anonymous>)
    at transform (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\index.js:28:26)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:194:22
    at Array.forEach (<anonymous>)
    at execTransforms (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:175:13)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:363:49
    at Array.forEach (<anonymous>)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:351:23
文件转换异常，规则：globalApi，文件：D:\Projects\typescript项目\vuex-module-decorators\src\module\index.ts TypeError: script.replace is not a function
    at Object.module.exports [as rule] (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\src\global-api.js:14:12)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\index.js:33:28
    at Array.reduce (<anonymous>)
    at transform (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\index.js:28:26)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:194:22
    at Array.forEach (<anonymous>)
    at execTransforms (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:175:13)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:363:49
    at Array.forEach (<anonymous>)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:351:23
文件转换异常，规则：lifeCycle，文件：D:\Projects\typescript项目\vuex-module-decorators\src\module\index.ts TypeError: script.find is not a function
    at Object.module.exports [as rule] (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\src\life-cycle.js:28:10)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\index.js:33:28
    at Array.reduce (<anonymous>)
    at transform (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\index.js:28:26)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:194:22
    at Array.forEach (<anonymous>)
    at execTransforms (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:175:13)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:363:49
    at Array.forEach (<anonymous>)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:351:23
文件转换异常，规则：renderFunctionApi，文件：D:\Projects\typescript项目\vuex-module-decorators\src\module\index.ts TypeError: scriptAst.find is not a function
    at Object.module.exports [as rule] (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\src\render-function-api.js:14:15)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\index.js:33:28
    at Array.reduce (<anonymous>)
    at transform (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\index.js:28:26)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:194:22
    at Array.forEach (<anonymous>)
    at execTransforms (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:175:13)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:363:49
    at Array.forEach (<anonymous>)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:351:23
文件转换异常，规则：vModel，文件：D:\Projects\typescript项目\vuex-module-decorators\src\module\index.ts TypeError: sourceAst.find is not a function
    at Object.module.exports [as rule] (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\src\v-model-pro.js:11:35)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\index.js:33:28
    at Array.reduce (<anonymous>)
    at transform (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\index.js:28:26)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:194:22
    at Array.forEach (<anonymous>)
    at execTransforms (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:175:13)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:363:49
    at Array.forEach (<anonymous>)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:351:23
文件转换异常，规则：watch，文件：D:\Projects\typescript项目\vuex-module-decorators\src\module\index.ts TypeError: sourceAst.find is not a function
    at Object.module.exports [as rule] (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\src\watch.js:4:33)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\index.js:33:28
    at Array.reduce (<anonymous>)
    at transform (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-plugin-vue\index.js:28:26)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:194:22
    at Array.forEach (<anonymous>)
    at execTransforms (D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:175:13)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:363:49
    at Array.forEach (<anonymous>)
    at D:\Program Files\nvm\v14.18.1\node_modules\gogocode-cli\src\commands\transform.js:351:23
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
5/11 D:\Projects\typescript项目\vuex-module-decorators\src\module\stateFactory.ts 881 B
6/11 D:\Projects\typescript项目\vuex-module-decorators\src\module\staticGenerators.ts 2393 B
7/11 D:\Projects\typescript项目\vuex-module-decorators\src\moduleoptions.ts 1087 B
8/11 D:\Projects\typescript项目\vuex-module-decorators\src\mutation.ts 612 B
9/11 D:\Projects\typescript项目\vuex-module-decorators\src\mutationaction.ts 3972 B
10/11 D:\Projects\typescript项目\vuex-module-decorators\src\vuexmodule.ts 1944 B
```

**Comment by wudi3** [comment]
vuex-module-decorators 最新版已经支持vue3和vuex4了 不需要gogocode进行转换 

![image](https://user-images.githubusercontent.com/6203854/142985785-a68af004-df61-4a02-906c-d5bac87742d5.png)
