### ISSUE TITLE
文件转换异常，规则：filters，文件：\src\public\mixins\global.js Error: replace failed: 

### ISSUE THREAD

**Issue by Tmac2015** [thx/gogocode#109]
报错内容是mixin 文件所有内容+' cannot be parsed!'
 cannot be parsed!
    at C:\Users\JDD\AppData\Roaming\npm\node_modules\gogocode-cli\node_modules\gogocode\src\js-core\core.js:279:31
    at Array.forEach (<anonymous>)
    at Object.replaceSelBySel (C:\Users\JDD\AppData\Roaming\npm\node_modules\gogocode-cli\node_modules\gogocode\src\js-core\core.js:196:22)
    at AST.replace (C:\Users\JDD\AppData\Roaming\npm\node_modules\gogocode-cli\node_modules\gogocode\src\Ast.js:419:19)
    at Object.addMethod (C:\Users\JDD\AppData\Roaming\npm\node_modules\gogocode-plugin-vue\utils\scriptUtils.js:69:15)
    at Object.module.exports [as rule] (C:\Users\JDD\AppData\Roaming\npm\node_modules\gogocode-plugin-vue\src\filters.js:60:33)
    at C:\Users\JDD\AppData\Roaming\npm\node_modules\gogocode-plugin-vue\index.js:33:28
    at Array.reduce (<anonymous>)
    at transform (C:\Users\JDD\AppData\Roaming\npm\node_modules\gogocode-plugin-vue\index.js:28:26)
    at C:\Users\JDD\AppData\Roaming\npm\node_modules\gogocode-cli\src\commands\transform.js:194:22

**Comment by wudi3** [comment]
能提供下\src\public\mixins\global.js 的代码片段吗？或者可以进钉钉群：34266233 讨论下
