### ISSUE TITLE
Bug Report From Playground: 解析html注释异常，并且会导致play崩溃！

### ISSUE THREAD

**Issue by zhangdaren** [thx/gogocode#110]
- version: 1.0.40
- playground demo: [link](https://play.gogocode.io/?v=1.0.40#code/N4IglgdgDgrgLgYQPYBMCmIBcIA8KwBuABAMYA2AhgM5UC8AOiBYwHwCMOA9PgS-RHkKlKNBk1YAmLjz4QQAGhAB3JACcA1snRYQAMxgQScMEghE4qihCq61AWwAUusGTQBJCLflEKUMN6QoY1MqAEoiYH4iUhC4IgASIlofPwA6AHMkTJJUNCiY6ziqJBhVEjQkomdXD1tU4tLy-JzCnyo45PiHBrK0b2AiKApVKjQAeSCTa0wIokoIdJgKdLQZgHIACzg7MjWiAF8D0PzqOFTVNChKcoc1wWJyajpGZhAWeIB9eOlCFjXvO4yT7fbi-NbHMxETicIgXOClMwATxKqnMlmstlUdjQKBi6CIGzQF3ycIRbTOKwgRIocDQDgh+34CnA0HgABkrOkdFsdsyNtQAApw4xErAWGB9EBUGAAIwAamA0EoACqIqAYbAWNAYfZAA)
- detail desc:
- 
``` html
<!--  加载搜索栏        ---->
```

上面的play地址可以无视，先把语言改成html，然后再输入上面这个注释放在play里面，然后就崩了。。。

在实际解析中。会报错：
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'content' of undefined
    at serializeCommentNode (E:\zpWork\Project_self\miniprogram-to-uniapp\node_modules\gogocode\src\html-core\serialize-node.js:22:39)
    at serializeNode (E:\zpWork\Project_self\miniprogram-to-uniapp\node_modules\gogocode\src\html-core\serialize-node.js:133:16)
    at E:\zpWork\Project_self\miniprogram-to-uniapp\node_modules\gogocode\src\html-core\serialize-node.js:106:20
    at Array.map (<anonymous>)
    at Object.serializeNode [as generate] (E:\zpWork\Project_self\miniprogram-to-uniapp\node_modules\gogocode\src\html-core\serialize-node.js:105:52)
    at AST.generate (E:\zpWork\Project_self\miniprogram-to-uniapp\node_modules\gogocode\src\Ast.js:726:57)
    at Page.generateTemplate (E:\zpWork\Project_self\miniprogram-to-uniapp\src\page\index.js:455:51)
……

**Comment by happyi** [comment]
我也遇到了
transform in progress: [============================================================================------] 597/641    TypeError: Cannot read property 'content' of undefined
    at serializeCommentNode (C:\Users\M004447\AppData\Roaming\nvm\v11.10.0\node_modules\gogocode-cli\node_modules\gogocode\src\html-core\serialize-node.js:22:39)
    at serializeNode (C:\Users\M004447\AppData\Roaming\nvm\v11.10.0\node_modules\gogocode-cli\node_modules\gogocode\src\html-core\serialize-node.js:133:16)
    at node.content.children.map.child (C:\Users\M004447\AppData\Roaming\nvm\v11.10.0\node_modules\gogocode-cli\node_modules\gogocode\src\html-core\serialize-node.js:106:20)
    at Array.map (<anonymous>)
    at serializeNode (C:\Users\M004447\AppData\Roaming\nvm\v11.10.0\node_modules\gogocode-cli\node_modules\gogocode\src\html-core\serialize-node.js:105:52)
    at node.content.children.map.child (C:\Users\M004447\AppData\Roaming\nvm\v11.10.0\node_modules\gogocode-cli\node_modules\gogocode\src\html-core\serialize-node.js:106:20)
    at Array.map (<anonymous>)
    at serializeNode (C:\Users\M004447\AppData\Roaming\nvm\v11.10.0\node_modules\gogocode-cli\node_modules\gogocode\src\html-core\serialize-node.js:105:52)
    at node.content.children.map.child (C:\Users\M004447\AppData\Roaming\nvm\v11.10.0\node_modules\gogocode-cli\node_modules\gogocode\src\html-core\serialize-node.js:106:20)
    at Array.map (<anonymous>)
