### ISSUE TITLE
filters规则转换异常

### ISSUE THREAD

**Issue by vivid05** [thx/gogocode#136]
文件转换异常，规则：filters，文件：/Users/wuxiansheng/project/fcash-system-web/src/views/report/collectReport/collectionTaskStatisticsOld.vue TypeError: expressionStatementAst.attr is not a function
    at /Users/wuxiansheng/.nvm/versions/node/v14.15.0/lib/node_modules/gogocode-plugin-vue/src/filters.js:77:59
    at Array.map (<anonymous>)
    at converFilterExpression (/Users/wuxiansheng/.nvm/versions/node/v14.15.0/lib/node_modules/gogocode-plugin-vue/src/filters.js:72:46)
    at /Users/wuxiansheng/.nvm/versions/node/v14.15.0/lib/node_modules/gogocode-plugin-vue/src/filters.js:124:42
    at Array.forEach (<anonymous>)
    at /Users/wuxiansheng/.nvm/versions/node/v14.15.0/lib/node_modules/gogocode-plugin-vue/src/filters.js:120:19
    at AST.each (/Users/wuxiansheng/.nvm/versions/node/v14.15.0/lib/node_modules/gogocode-cli/node_modules/gogocode/src/Ast.js:73:13)
    at Object.module.exports [as rule] (/Users/wuxiansheng/.nvm/versions/node/v14.15.0/lib/node_modules/gogocode-plugin-vue/src/filters.js:118:40)
    at /Users/wuxiansheng/.nvm/versions/node/v14.15.0/lib/node_modules/gogocode-plugin-vue/index.js:42:28
    at Array.reduce (<anonymous>)

**Comment by zhuscat** [comment]
#154
