### ISSUE TITLE
vue2升级到vue3 及 升级到element-plus后,执行 npm run dev 报错

### ISSUE THREAD

**Issue by 1719448063** [thx/gogocode#191]
- PS D:\project\vue-admin-template> npm run dev

 INFO  Starting development server...
 ERROR  Error: Cannot call .tap() on a plugin that has not yet been defined. Call plugin('preload').use(<Plugin>) first.
Error: Cannot call .tap() on a plugin that has not yet been defined. Call plugin('preload').use(<Plugin>) first.
    at Object.tap (D:\project\vue-admin-template\node_modules\webpack-chain\src\Plugin.js:26:15)
    at chainWebpack (D:\project\vue-admin-template\vue.config.js:53:30)
    at D:\project\vue-admin-template\node_modules\@vue\cli-service\lib\Service.js:268:40
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (D:\project\vue-admin-template\node_modules\@vue\cli-service\lib\Service.js:268:26)        
    at Service.resolveWebpackConfig (D:\project\vue-admin-template\node_modules\@vue\cli-service\lib\Service.js:272:48)
    at PluginAPI.resolveWebpackConfig (D:\project\vue-admin-template\node_modules\@vue\cli-service\lib\PluginAPI.js:132:25)
    at serve (D:\project\vue-admin-template\node_modules\@vue\cli-service\lib\commands\serve.js:79:31)
    at Service.run (D:\project\vue-admin-template\node_modules\@vue\cli-service\lib\Service.js:262:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by duanwujie** [comment]
Me too

**Comment by zhikunking** [comment]
怎么解决啊

**Comment by 1719448063** [comment]
我反正是放弃了  直接用最新的vue3脚手架重新搭了一套....
