### ISSUE TITLE
bug in gogocode-plugin-vue SyntaxError: ';' expected. (5:40)

### ISSUE THREAD

**Issue by masx200** [thx/gogocode#46]
gogocode-plugin-vue 1.0.10
 gogocode-cli 0.2.17

```shell

gogocode -s ./src/index.ts -t gogocode-plugin-vue -o ./src-out/index.ts
```

```text


transform start

transform error: /home/mas/Documents/my-vue-router-project/src/index.ts
SyntaxError: ';' expected. (5:40)
  3 | import { initloadingid } from "./initloadingid.ts";
  4 | import "./error-alert.js";
> 5 | import * as VueRouter from 'vue-router'import * as Vue from 'vue';
    |                                        ^
  6 | import "@masx200/webpack-react-vue-spa-awesome-config/registerserviceworker.js";
  7 |
  8 | // import "webpack-react-vue-spa-awesome-config/ie11babelpolyfill";
    at e (/home/mas/Downloads/node-v16.5.0-linux-x64/node-v16.5.0-linux-x64/lib/node_modules/gogocode-plugin-vue/node_modules/prettier/parser-typescript.js:1:322)
    at /home/mas/Downloads/node-v16.5.0-linux-x64/node-v16.5.0-linux-x64/lib/node_modules/gogocode-plugin-vue/node_modules/prettier/parser-typescript.js:22:3248894
    at Object.parse (/home/mas/Downloads/node-v16.5.0-linux-x64/node-v16.5.0-linux-x64/lib/node_modules/gogocode-plugin-vue/node_modules/prettier/parser-typescript.js:22:3248927)
    at Object.parse$a [as parse] (/home/mas/Downloads/node-v16.5.0-linux-x64/node-v16.5.0-linux-x64/lib/node_modules/gogocode-plugin-vue/node_modules/prettier/index.js:13684:19)
    at coreFormat (/home/mas/Downloads/node-v16.5.0-linux-x64/node-v16.5.0-linux-x64/lib/node_modules/gogocode-plugin-vue/node_modules/prettier/index.js:15215:16)
    at formatWithCursor$1 (/home/mas/Downloads/node-v16.5.0-linux-x64/node-v16.5.0-linux-x64/lib/node_modules/gogocode-plugin-vue/node_modules/prettier/index.js:15455:14)
    at /home/mas/Downloads/node-v16.5.0-linux-x64/node-v16.5.0-linux-x64/lib/node_modules/gogocode-plugin-vue/node_modules/prettier/index.js:60228:12
    at Object.format (/home/mas/Downloads/node-v16.5.0-linux-x64/node-v16.5.0-linux-x64/lib/node_modules/gogocode-plugin-vue/node_modules/prettier/index.js:60248:12)
    at transform (/home/mas/Downloads/node-v16.5.0-linux-x64/node-v16.5.0-linux-x64/lib/node_modules/gogocode-plugin-vue/index.js:47:30)
    at /home/mas/Downloads/node-v16.5.0-linux-x64/node-v16.5.0-linux-x64/pnpm-global/5/node_modules/.pnpm/gogocode-cli@0.2.17/node_modules/gogocode-cli/src/commands/transform.js:196:22 {
  loc: { start: { line: 5, column: 40 } },
  codeFrame: '\x1B[0m \x1B[90m 3 |\x1B[39m \x1B[36mimport\x1B[39m { initloadingid } \x1B[36mfrom\x1B[39m \x1B[32m"./initloadingid.ts"\x1B[39m\x1B[33m;\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 4 |\x1B[39m \x1B[36mimport\x1B[39m \x1B[32m"./error-alert.js"\x1B[39m\x1B[33m;\x1B[39m\x1B[0m\n' +
    "\x1B[0m\x1B[31m\x1B[1m>\x1B[22m\x1B[39m\x1B[90m 5 |\x1B[39m \x1B[36mimport\x1B[39m \x1B[33m*\x1B[39m \x1B[36mas\x1B[39m \x1B[33mVueRouter\x1B[39m \x1B[36mfrom\x1B[39m \x1B[32m'vue-router'\x1B[39m\x1B[36mimport\x1B[39m \x1B[33m*\x1B[39m \x1B[36mas\x1B[39m \x1B[33mVue\x1B[39m \x1B[36mfrom\x1B[39m \x1B[32m'vue'\x1B[39m\x1B[33m;\x1B[39m\x1B[0m\n" +                                                                           
    '\x1B[0m \x1B[90m   |\x1B[39m                                        \x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 6 |\x1B[39m \x1B[36mimport\x1B[39m \x1B[32m"@masx200/webpack-react-vue-spa-awesome-config/registerserviceworker.js"\x1B[39m\x1B[33m;\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 7 |\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 8 |\x1B[39m \x1B[90m// import "webpack-react-vue-spa-awesome-config/ie11babelpolyfill";\x1B[39m\x1B[0m'
}

transform failed!

```
```ts
import "./styles.ts";
//@ts-ignore
import { initloadingid } from "./initloadingid.ts";
import "./error-alert.js";
import VueRouter from "vue-router";
//@ts-ignore
// import SimpleStoreManager from "@masx200/vue-simple-global-state-store-manager"; // bindGlobalStore // initGlobalState,
import Vue from "vue";
import "@masx200/webpack-react-vue-spa-awesome-config/registerserviceworker.js";

// import "webpack-react-vue-spa-awesome-config/ie11babelpolyfill";
("use strict");
const rootele =
    document.getElementById("root") ||
    document.body.appendChild(document.createElement("div"));
Object.assign(rootele, { id: "root" });
if (!document.getElementById("app")) {
    rootele &&
        (rootele.innerHTML = `<div id=${initloadingid}>
<h1>loading</h1>
<span class="mui-spinner mui-spinner-custom">

</span></div>`);
}
// eslint-disable-next-line no-undef

window.addEventListener(
    "load",
    () => {
        //   import("bootstrap/dist/js/bootstrap.bundle");
        import("clipboard").then((module) => {
            const ClipboardJS = module.default;
            new ClipboardJS(".btn").on("success", function (e) {
                e.clearSelection();
            });
        });
    },
    { once: true }
);

Vue.config.productionTip = false;
Vue.config.silent = true;
Vue.config.devtools = true;
Vue.use(VueRouter);
// console.log(SimpleStore);
// Vue.use(SimpleStoreManager);
Vue.config.errorHandler = function (err, vm, info) {
    throw err;
};
import("./vue-index-render.js").then(({ router, default: AppHome }) => {
    const container =
        document.getElementById("app") ||
        rootele.appendChild(document.createElement("div"));
    Object.assign(container, { id: "app" });
    // var AppHome=default
    const vm = new Vue({
        router,

        render(h) {
            return h(AppHome);
        },
    });
    rootele && vm.$mount(container);
    Object.assign(vm.$el, {
        id: "app",
    });
});

```

**Comment by masx200** [comment]
在我调整了一下文件之后发现转化成功了，但是转化有亿点问题：

1.没有转化`new Vue`

2.少了一句话`Vue.use(VueRouter);`

```ts
import '@masx200/webpack-react-vue-spa-awesome-config/registerserviceworker.js'
import * as Vue from 'vue'
import * as VueRouter from 'vue-router'
import './error-alert.js'
//@ts-ignore
import { initloadingid } from './initloadingid.ts'
import './styles.ts'

// import "webpack-react-vue-spa-awesome-config/ie11babelpolyfill";
;('use strict')
const rootele =
  document.getElementById('root') ||
  document.body.appendChild(document.createElement('div'))
Object.assign(rootele, { id: 'root' })
if (!document.getElementById('app')) {
  rootele &&
    (rootele.innerHTML = `<div id=${initloadingid}>
<h1>loading</h1>
<span class="mui-spinner mui-spinner-custom">

</span></div>`)
}
// eslint-disable-next-line no-undef

window.addEventListener(
  'load',
  () => {
    //   import("bootstrap/dist/js/bootstrap.bundle");
    import('clipboard').then((module) => {
      const ClipboardJS = module.default
      new ClipboardJS('.btn').on('success', function (e) {
        e.clearSelection()
      })
    })
  },
  { once: true }
)

window.$vueApp.config.silent = true
window.$vueApp.config.devtools = true
// console.log(SimpleStore);
// Vue.use(SimpleStoreManager);
window.$vueApp.config.errorHandler = function (err, vm, info) {
  throw err
}
import('./vue-index-render.js').then(({ router, default: AppHome }) => {
  const container =
    document.getElementById('app') ||
    rootele.appendChild(document.createElement('div'))
  Object.assign(container, { id: 'app' })
  // var AppHome=default
  const vm = new Vue({
    router,

    render() {
      return Vue.h(AppHome)
    },
  })
  rootele && vm.$mount(container)
  Object.assign(vm.$el, {
    id: 'app',
  })
})


```

**Comment by wudi3** [comment]
重新执行即可
gogocode -s ./src/index.ts -t gogocode-plugin-vue -o ./src-out/index.ts

gogocode-plugin-vue 已经更新至 1.0.11 修复了该bug
