### ISSUE TITLE
tiny-emitter/instance和入口文件的问题

### ISSUE THREAD

**Issue by fz6m** [thx/gogocode#50]
#### 依赖问题

运行 `gogocode -s package.json -t gogocode-plugin-vue -o package.json` 给我加了个啥 `tiny-emitter/instance` 依赖，npm 上没有：

![image](https://user-images.githubusercontent.com/59400654/126871197-32231dc6-4c48-4406-9091-e23f82235749.png)

#### 入口文件问题

```js
transform in progress: [===========----------] 11/21    文件转换异常，规则：globalApi，文件：/Users/username/Documents/development/code/test/vue/migration/project/src/main.js TypeError: Cannot read property 'type' of null
    at AST.insertSiblingNode (/usr/local/lib/node_modules/gogocode-cli/node_modules/gogocode/src/Ast.js:447:70)
    at /usr/local/lib/node_modules/gogocode-cli/node_modules/gogocode/src/Ast.js:504:18
    at Array.forEach (<anonymous>)
    at AST.after (/usr/local/lib/node_modules/gogocode-cli/node_modules/gogocode/src/Ast.js:503:14)
    at /usr/local/lib/node_modules/gogocode-plugin-vue/src/global-api.js:50:34
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/gogocode-plugin-vue/src/global-api.js:46:28
    at AST.each (/usr/local/lib/node_modules/gogocode-cli/node_modules/gogocode/src/Ast.js:73:13)
    at Object.module.exports [as rule] (/usr/local/lib/node_modules/gogocode-plugin-vue/src/global-api.js:32:44)
    at /usr/local/lib/node_modules/gogocode-plugin-vue/index.js:33:28
transform in progress: [=====================] 21/21    
```

可以看下这个 case 存在什么转换问题（原入口文件）：

```js
import Vue from 'vue'
import App from './App.vue'
import router from './router'
import store from './store'
import './registerServiceWorker'
import i18n from './i18n'
import './registerServiceWorker'
import VueCookies from 'vue-cookies'
import '@mdi/font/css/materialdesignicons.css'
import SoftUI from './components/SoftUI'
import axios from 'axios'
import VueAxios from 'vue-axios'
Vue.use(VueCookies)
Vue.use(SoftUI)
Vue.use(VueAxios, axios)
Vue.config.productionTip = false

new Vue({
    router,
    store,
    i18n,
    data: function() {
        return {
            dark: false,
        }
    },
    render: h => h(App)
}).$mount('#app')
```

**Comment by eyis** [comment]
> tiny-emitter/instance

tiny-emitter/instance 的引用麻烦您修改为 tiny-emitter

相关npm包为 https://www.npmjs.com/package/tiny-emitter
gogocode-plugin-vue后续1.0.13版本修复此问题

**Comment by eyis** [comment]
另外入口文件的转换我试了下没有报错，请也升级一下gogocode-cli的最新版试试
npm install gogocode-cli -g
