### ISSUE TITLE
TypeError: Cannot read property 'content' of undefined

### ISSUE THREAD

**Issue by Trinidad233** [thx/gogocode#67]
transform in progress: [==========================================================-] 58/59    TypeError: Cannot read property 'content' of undefined
    at serializeCommentNode (/usr/local/lib/node_modules/gogocode-cli/node_modules/gogocode/src/html-core/serialize-node.js:22:39)
    at serializeNode (/usr/local/lib/node_modules/gogocode-cli/node_modules/gogocode/src/html-core/serialize-node.js:121:16)
    at /usr/local/lib/node_modules/gogocode-cli/node_modules/gogocode/src/html-core/find.js:21:101
    at Array.map (<anonymous>)
    at /usr/local/lib/node_modules/gogocode-cli/node_modules/gogocode/src/html-core/find.js:21:92
    at Array.every (<anonymous>)
    at checkIsMatch (/usr/local/lib/node_modules/gogocode-cli/node_modules/gogocode/src/html-core/find.js:11:33)
    at /usr/local/lib/node_modules/gogocode-cli/node_modules/gogocode/src/html-core/find.js:69:49
    at Array.every (<anonymous>)
    at checkIsMatch (/usr/local/lib/node_modules/gogocode-cli/node_modules/gogocode/src/html-core/find.js:11:33)
transform error: /root/dev/cydex-web/cydex-admin copy/src/views/company/list.vue
TypeError: Cannot read property 'content' of undefined
    at serializeCommentNode (/usr/local/lib/node_modules/gogocode-cli/node_modules/gogocode/src/html-core/serialize-node.js:22:39)
    at serializeNode (/usr/local/lib/node_modules/gogocode-cli/node_modules/gogocode/src/html-core/serialize-node.js:121:16)
    at /usr/local/lib/node_modules/gogocode-cli/node_modules/gogocode/src/html-core/serialize-node.js:94:20
    at Array.map (<anonymous>)
    at serializeNode (/usr/local/lib/node_modules/gogocode-cli/node_modules/gogocode/src/html-core/serialize-node.js:93:52)
    at /usr/local/lib/node_modules/gogocode-cli/node_modules/gogocode/src/html-core/serialize-node.js:94:20
    at Array.map (<anonymous>)
    at serializeNode (/usr/local/lib/node_modules/gogocode-cli/node_modules/gogocode/src/html-core/serialize-node.js:93:52)
    at Object.toString [as generate] (/usr/local/lib/node_modules/gogocode-cli/node_modules/gogocode/src/vue-core/generate.js:33:28)
    at AST.generate (/usr/local/lib/node_modules/gogocode-cli/node_modules/gogocode/src/Ast.js:680:57)
transform in progress: [===========================================================] 59/59

**Comment by wudi3** [comment]
可以进钉钉群：34266233，把代码发给我们看下。

**Comment by happyi** [comment]
我也遇到了
transform in progress: [============================================================================------] 597/641    TypeError: Cannot read property 'content' of undefined
    at serializeCommentNode (C:\Users\M004447\AppData\Roaming\nvm\v11.10.0\node_modules\gogocode-cli\node_modules\gogocode\src\html-core\serialize-node.js:22:39)
    at serializeNode (C:\Users\M004447\AppData\Roaming\nvm\v11.10.0\node_modules\gogocode-cli\node_modules\gogocode\src\html-core\serialize-node.js:133:16)
    at node.content.children.map.child (C:\Users\M004447\AppData\Roaming\nvm\v11.10.0\node_modules\gogocode-cli\node_modules\gogocode\src\html-core\serialize-node.js:106:20)
    at Array.map (<anonymous>)
    at serializeNode (C:\Users\M004447\AppData\Roaming\nvm\v11.10.0\node_modules\gogocode-cli\node_modules\gogocode\src\html-core\serialize-node.js:105:52)
    at node.content.children.map.child (C:\Users\M004447\AppData\Roaming\nvm\v11.10.0\node_modules\gogocode-cli\node_modules\gogocode\src\html-core\serialize-node.js:106:20)
    at Array.map (<anonymous>)
    at serializeNode (C:\Users\M004447\AppData\Roaming\nvm\v11.10.0\node_modules\gogocode-cli\node_modules\gogocode\src\html-core\serialize-node.js:105:52)
    at node.content.children.map.child (C:\Users\M004447\AppData\Roaming\nvm\v11.10.0\node_modules\gogocode-cli\node_modules\gogocode\src\html-core\serialize-node.js:106:20)
    at Array.map (<anonymous>)

**Comment by psz-dxc** [comment]
如何解决的？
